version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: personalnest-postgres-16.3
    environment:
      POSTGRES_DB: personalnest
      POSTGRES_USER: personalnest
      POSTGRES_PASSWORD: personalnest
    ports:
      - '5432:5432' # Expose the database port to the host
    volumes:
      - personalnest:/var/lib/postgresql/data

volumes:
  personalnest:
